apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
- name: artifactory-credential-provider
  matchImages:
    - "your-jfrog-instance.jfrog.io"
  defaultCacheDuration: "10m"
  apiVersion: credentialprovider.kubelet.k8s.io/v1
