# https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/
apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
- name: artifactory-credential-provider
  matchImages:
    - "your-jfrog-instance.jfrog.io/docker-repo/"
  defaultCacheDuration: "10m"
  apiVersion: credentialprovider.kubelet.k8s.io/v1
  env:
    - name: ID_TOKEN_PROVIDER
      value: "GCP-GCE"
    - name: ID_TOKEN_TARGET_AUDIENCE
      value: "artifactory-idp"
    - name: ARTIFACTORY_URL
      value: "https://your-jfrog-instance.jfrog.io"
    - name: ARTIFACTORY_OIDC_PROVIDER
      value: "no-idea"
    - name: ARTIFACTORY_PROJECT_KEY
      value: "project-key"
