name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build & Deploy
        run: |
          pushd src/installer
          go mod tidy
          go test -v
          go build -o ../../out/installer
          popd

          pushd src/provider
          go mod tidy
          go test -v
          go build -o ../../out/artifactory-credential-provider
          popd

          docker build . -t registry.m3y3r.de/artifactory-credential-provider:latest
          docker login registry.m3y3r.de -u "{{ secrets.DOCKER_USERNAME }}" --password-stdin <<< "{{ secrets.DOCKER_PASSWORD }}"
          docker push registry.m3y3r.de/artifactory-credential-provider:latest
