name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      artifactoryUrl:
        description: 'Artifactory URL'
        required: true
        type: string
      artifactoryOidcProvider:
        description: 'Artifactory OIDC provider name'
        required: true
        type: string
      artifactoryProjectKey:
        description: 'Artifactory project key'
        required: true
        type: string

permissions:
  id-token: write     # Allows workflows to request an OIDC token
  contents: read      # Typically required for accessing repository content

jobs:
  build:
    name: Build and Test Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v ./...  # Run all tests to ensure the build is stable

      - name: Build Project
        run: go build -o ./out/artifactory-credential-provider

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: ./out

      - name: Test Integration
        if: github.event_name == 'workflow_dispatch'
        run: |
          ID_TOKEN_PROVIDER=GitHub
          ID_TOKEN_TARGET_AUDIENCE=artifactory-idp
          ARTIFACTORY_URL="${{ github.event.inputs.artifactoryUrl }}"
          ARTIFACTORY_OIDC_PROVIDER="${{ github.event.inputs.artifactoryOidcProvider }}"
          ARTIFACTORY_PROJECT_KEY="${{ github.event.inputs.artifactoryProjectKey }}"
          echo '{"apiVersion": "credentialprovider.kubelet.k8s.io/v1", "kind": "CredentialProviderRequest", "image": "example/image:latest"}' | ./out/artifactory-credential-provider
